apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-app
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:15.1
  enableSuperuserAccess: true 
  bootstrap:
    initdb:
      database: airflow
      owner: airflow
  storage:
    size: 1Gi
  resources:
    limits:
      cpu: "1"  # Added CPU limits for consistency
      memory: 1Gi
    requests:
      cpu: "250m"  # Added CPU requests for consistency
      memory: 256Mi