controller:
  ingressClassResource:
    name: nginx-internal
    controllerValue: k8s.io/ingress-nginx-internal
    default: true
    enabled: true
  replicaCount: 1
  ingressClassByName: true
  electionID: ingress-internal-leader
  
tcp:
  50000: cnpg/pg-app-rw:5432 #namespace/service

    
      